---
title: "Previsão de cancelamento de reservas de hotel"
author: "Guilherme Luz"
date: "7/12/2021"
output: 
  pdf_document: 
    keep_tex: true
geometry: margin=1in
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = T, echo = FALSE, tidy = TRUE, tidy.opts = list(width.cutoff = 60), warning = T)
```

# Introdução

O objetivo deste relatório é apresentar um modelo preditivo para cancelamento de reserva de hotéis...

# Base de dados

```{r, include=FALSE}
library(tidyverse)
library(stargazer)
library(caret)
library(knitr)
library(kableExtra)
```

```{r}
set.seed(1444)
```

```{r, include=FALSE}
data0 = read_csv( "hotel_booking_clean.csv", quote='"', col_types = cols(agent = "c", company = "c"))
```

```{r, results= 'asis'}
#descriptive stats - numeric variables
numeric_variables = (map_df(data0, class) == "numeric") %>% as.vector()
data0[ , numeric_variables] %>%
  data.frame() %>%
  stargazer( type = "latex", title = "Estatísticas das variáveis numéricas", label = "tab1", header = FALSE)
```

```{r}
#descriptive stats - categorical variables
categ_variables = (map_df(data0, class) == "character") %>% as.vector()
categ_variables = colnames(data0)[categ_variables]

estats = matrix(NA, nrow = length(categ_variables), ncol = 7) %>% 
  data.frame() %>%
  setNames( c("Variable", "Unique", "type 1", "type 2", "type 3", "type 4", "type 5") )
estats$Variable <- categ_variables
for (i in categ_variables){
  estats[estats$Variable==i, "Unique"] <- unique(data0[[i]]) %>%length()
  tab = table(as.factor(data0[[i]])) 
  index = order(tab, decreasing = T) %>% head(5)
  tab = paste(names(tab[index]), tab[index], sep = ": ")
  for (j in 1:5){
    estats[estats$Variable==i, (2+j)] <- tab[j]
  }
}

kable( estats, caption = 'Estatísticas decritivas de variáveis categoricas' , booktabs = T)%>% 
		kable_styling(latex_options="scale_down") %>%
  footnote(general = '"Unique" indica o número de categorias únicas de cada variável. "Type" apresenta um exemplo de um categoria espeícifca e seu número de observações, em ordem decrescente de frequencia na base de dados.', threeparttable = T)
```


<!-- Dummies -->

```{r}
#mudando variaveis agent & company 
#elas vao indicar 1 se a reserva veio de um agente ou uma companhia; 0 caso o contrário

data0$agent <- ifelse(data0$agent == "0", 0, 1)
data0$company <- ifelse(data0$company == "0", 0, 1)

#mudando country
data0$portugal <- ifelse(data0$country == "PRT", 1, 0)
europe = readxl::read_excel("codigo_europa.xlsx")
data0$europe <- ifelse((data0$country %in% europe$code) &
                         (data0$country != "PRT"), 
                       1, 0)

data0 = select(data0, -country)
rm(europe)
```

```{r, warning=FALSE}
#removendo variaveis colineares e y alternativos
data = data0 %>% select(-reservation_status, -reservation_status_date, -arrival_date, -arrival_date_week_number, -is_repeated_guest)
#criando dummies
categ_variables = (map_df(data0, class) == "character") %>% as.vector()
categ_variables = colnames(data0)[categ_variables]

data = fastDummies::dummy_cols(data, 
            select_columns = categ_variables, 
            remove_first_dummy = TRUE, remove_selected_columns = TRUE)
```

<!-- Separando train e test -->

\textcolor{red}{trabalhando com a base reduzida: 10.000 obs}
```{r, include = T}
data = sample_n(data, 10000, replace = F)
```

```{r}
#create train/test sets
train_index = sample(1:nrow(data), nrow(data)*0.8, 
                     replace = F)
train = data[train_index, ]
test = data[-train_index, ]
```

```{r}
X = train %>% select(-is_canceled) %>% as.matrix() 
Y = train$is_canceled %>% as.factor()
X_test = test %>% select(-is_canceled) %>% as.matrix()
Y_test = test$is_canceled %>% as.factor()

#para usar nos outros arquivos:
tidy_data = list(X, Y, X_test, Y_test)
saveRDS(tidy_data, "tidy_data")
```

```{r}
X %>%
  scale(center = T, scale = T) %>% data.frame() %>%
  select(1:18) %>%
gather(  key = "Variable", value = "Value" ) %>%
  ggplot(aes(x = Variable, y = Value))+
    geom_boxplot()+
    theme( axis.text.x = element_text( size = 5, angle = 90) )+
  ggtitle("Dispersão após a padronização")
```










